# 1 引入numpy并查看版本
```
out:1.17.3
```

In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.1'

# 2 创建一位数组，0-9
```
out:array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3 创建boolean数组（3x3全部为True）
```
out:array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])
```

In [6]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 4 提取满足条件的元素（提取奇数项）
```
in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out:   array([1, 3, 5, 7, 9])
```

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [32]:
arr2 = arr*2
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr[arr2%2==1]  #通过元素计算，而非下标

array([], dtype=int64)

# 5 替换满足条件的元素（替换奇数项为-1）
```
in: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out:array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])
```

In [39]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr[1::2]= -1

In [41]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [42]:
index = np.arange(len(arr)) # 通过index计算
arr[index%2 ==1] =-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6 与5相同，但是不要在原数组上改动，返回个新的数组

In [35]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
sub = arr[:]
sub[1::2]= -1
sub

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [43]:
index = np.arange(len(arr)) # 通过index计算
res = np.where(index%2==1,-1,arr) # 新函数!!
res

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 7 reshape一个数组（0-9这个一维数组->2x5的二维数组）
```
in: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out: array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8 垂直拼接俩数组
```
in: a = np.arange(10).reshape(2,-1)
   b = np.repeat(1, 10).reshape(2,-1)
out: array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)  # 新函数

In [22]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 9 水平拼接俩数组
```
in: a = np.arange(10).reshape(2,-1)
   b = np.repeat(1, 10).reshape(2,-1)
out: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [24]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# 10 生成自定义的数组
```
in: a = np.array([1,2,3])
out: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [44]:
a = np.array([1,2,3])

In [45]:
np.hstack([np.repeat(a,3) ,a,a,a])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11 求两数组交集
```
in: a = np.array([1,2,3,2,3,4,3,4,5,6])
   b = np.array([7,2,10,2,7,4,9,4,9,8])
out:array([2, 4])
```

In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [47]:
np.intersect1d(a,b)

array([2, 4])

# 12 从一个数组中删除另一个数组中含有的元素
```
in: a = np.array([1,2,3,4,5])
   b = np.array([5,6,7,8,9])
out:array([1,2,3,4])
```

In [48]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [50]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

# 13 两等长数组，找出位置相同且值也相同的下标
```
in: a = np.array([1,2,3,2,3,4,3,4,5,6])
   b = np.array([7,2,10,2,7,4,9,4,9,8])
out:(array([1, 3, 5, 7]),)
```

In [52]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [53]:
np.where(a == b)

(array([1, 3, 5, 7]),)

# 14 提取给定范围的数据(提取值在5-10之间的元素)
```
in: a = np.array([2, 6, 1, 9, 10, 3, 27])
out:(array([6, 9, 10]),)
```

In [54]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [55]:
a[(a >=5 ) & (a <=10)]

array([ 6,  9, 10])

# 15 取a,b两等长数组中较大值为新数组
```
in: a = [4,6,1,7,9]
b=[1,6,9,2,7]
```

In [59]:
a = [4,6,1,7,9]
b=[1,6,9,2,7]

In [62]:
np.max(np.vstack([a,b]),axis=0)

array([4, 6, 9, 7, 9])

# 16 如何交换二维数组两列（交换3x3数组的第0和第1列）
```
in:arr = np.arange(9).reshape(3,3)
out:array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])
       ```

In [64]:
arr = np.arange(9).reshape(3,3)

In [65]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# 17 如何交换二维数组两行（交换3x3数组第0和第1行）
```
in:arr = np.arange(9).reshape(3,3)
out:array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])
```

In [66]:
arr =np.arange(9).reshape(3,3)

In [67]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# 18 如何反转二维数组的行
```
in:arr = np.arange(9).reshape(3,3)
out:array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])
```

In [68]:
arr =np.arange(9).reshape(3,3)

In [69]:
arr[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

# 19  如何反转二维数组的列
```
in:arr = np.arange(9).reshape(3,3)
out:array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])
       ```

In [70]:
arr =np.arange(9).reshape(3,3)

In [71]:
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 20 创建5x3的float二维数组，值是5-10的随机数

In [72]:
np.random.randint(5,11,15).reshape(5,3)

array([[ 6,  8,  9],
       [10, 10,  7],
       [ 7,  9,  7],
       [ 5,  9,  7],
       [ 5,  8,  7]])

In [73]:
np.random.uniform(5,10,(5,3))

array([[8.36189438, 8.36356932, 7.62779084],
       [7.52979788, 6.49947576, 5.77024321],
       [6.942666  , 6.78994417, 8.24682838],
       [6.58191915, 9.76396628, 6.44756139],
       [7.10661326, 9.74921338, 8.43203359]])

# 21 [打印设置相关]float数组每个元素保留小数点后3位打印(只是打印时，本质不变)
```
in:rand_arr = np.random.random((5,3))
```

In [74]:
rand_arr = np.random.random((5,3))

In [75]:
np.set_printoptions(precision=3)
rand_arr

array([[0.019, 0.926, 0.049],
       [0.544, 0.206, 0.991],
       [0.438, 0.949, 0.733],
       [0.985, 0.071, 0.596],
       [0.557, 0.103, 0.769]])

# 22 [打印设置相关]避免科学计数法打印数组
```
in:np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
```

In [76]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [77]:
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [78]:
np.set_printoptions(suppress=True, precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# 23 [打印设置相关]如何限制数组打印条数
```
in:a = np.arange(15)
out: array([ 0,  1,  2, ..., 12, 13, 14])
```

In [79]:
a = np.arange(15)

In [80]:
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

# 24 [打印设置相关]如何打印全部数据避免被省略

In [81]:
np.set_printoptions(threshold=1000)
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# 25 导入含有数字和文本的数据集，保证数据完整(不要让文本变nan了)
```
in:url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
```

In [82]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [84]:
np.set_printoptions(threshold=6)
iris = np.genfromtxt(url,delimiter=',',dtype='object')
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

# 26 一维tuple数组，提取特定一列
```
in:url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
```

In [85]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

/home/yichang/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [86]:
species = np.array([row[4] for row in iris_1d])
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

# 27 如何将一维tuple数组转二维
```
in:同26
```

In [87]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)

/home/yichang/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [88]:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

# 28 计算数组均值、中位数、标准差
```
in: np.arange(1000)
out:499.5 499.5 288.6749902572095
```

In [89]:
a = np.arange(1000)
(np.mean(a), np.median(a), np.std(a))

(499.5, 499.5, 288.6749902572095)

# 29 数组归一化
```
in:a = np.arange(15)
a = a.reshape(3,5)
out:array([[0.      , 0.071429, 0.142857, 0.214286, 0.285714],
       [0.357143, 0.428571, 0.5     , 0.571429, 0.642857],
       [0.714286, 0.785714, 0.857143, 0.928571, 1.      ]])
```

In [90]:
a = np.arange(15)
a = a.reshape(3,5)

In [91]:
ma = a.max()
mi = a.min()
(a - mi)/(ma - mi)

array([[0.      , 0.071429, 0.142857, 0.214286, 0.285714],
       [0.357143, 0.428571, 0.5     , 0.571429, 0.642857],
       [0.714286, 0.785714, 0.857143, 0.928571, 1.      ]])

# 30 如何计算softmax分数

In [92]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

In [93]:
sepallength[:5]

array([5.1, 4.9, 4.7, 4.6, 5. ])

In [94]:
# 对向量进行归一化，凸显其中最大的值并抑制远低于最大值的其他分量。
# 重要函数
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

In [96]:
np.set_printoptions(threshold=1000)
softmax(sepallength[:10])

array([0.122295, 0.100127, 0.081977, 0.074176, 0.110657, 0.165081,
       0.074176, 0.110657, 0.06073 , 0.100127])

# 31找到第5%和第95%大的值

```
in:a = np.random.rand(100)
```

In [97]:
a = np.random.rand(100)
np.percentile(a,q=[5,95])

array([0.059188, 0.975081])

# 32 如何在随机位置改值，在一个数组中随机10个位置改为nan
```
in: a = np.random.rand(100)
```

In [98]:
a = np.random.rand(100)

In [99]:
np.set_printoptions(threshold=10)
a[np.random.randint(100,size=10)]=np.nan
a

array([0.166694, 0.023178, 0.160745, ..., 0.301752, 0.979624, 0.035627])

# 33 找出数组中nan的位置
```
in: a = np.random.rand(100)
a[np.random.randint(100, size=20)] = np.nan
out: 20
```

In [100]:
a = np.random.rand(100)
a[np.random.randint(100, size=20)] = np.nan

In [101]:
np.where(np.isnan(a))

(array([ 0,  1,  7, ..., 87, 90, 98]),)

# 34 使用2个或以上条件来过滤数组元素
```
in: a = np.random.rand(100)
out:在>0.2 且 <0.8
```

In [102]:
a = np.random.rand(100)

In [104]:
a[(a>0.2) & (a < 0.8)] #必须有括号

array([0.699632, 0.271694, 0.599993, ..., 0.266454, 0.657147, 0.748506])

# 35 删除含有nan的行
```
in:a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
```

In [105]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)

In [107]:
index = [~np.any(np.isnan(row)) for row in a]
index

[True, True, True, False, True, True, False, False, True, False]

In [108]:
a[index]

array([[0.934542, 0.896985, 0.343623, ..., 0.563431, 0.455038, 0.341985],
       [0.623383, 0.21236 , 0.133043, ..., 0.025134, 0.270897, 0.958288],
       [0.989244, 0.524229, 0.116979, ..., 0.220498, 0.561125, 0.720267],
       [0.685852, 0.410708, 0.882639, ..., 0.015783, 0.264345, 0.42559 ],
       [0.912524, 0.263556, 0.271085, ..., 0.424459, 0.244018, 0.274413],
       [0.810186, 0.121511, 0.010492, ..., 0.688104, 0.13497 , 0.008719]])

# 36 求两列相关性(如第0和第2列相关性)
```
in:a = np.random.rand(100)
a = a.reshape(10,10)
```

In [110]:
a = np.random.rand(100)
a = a.reshape(10,10)

In [113]:
np.corrcoef(a[:,0],a[:,2]) # 返回一个相关性矩阵：1与1，1与2，2与1，2与2 的相关性

array([[ 1.      , -0.190487],
       [-0.190487,  1.      ]])

# 37 判断数组是否有nan值
```
in:a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
```

In [114]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)

In [115]:
np.isnan(a).any()

True

# 38 将数组中的nan全部替换为0

In [116]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)

In [117]:
a[np.isnan(a)]=0

# 39 求数组不重复值个数
```
in: a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')
```

In [118]:
a = np.random.rand(100) # [0,1]之前生成100个树
a[np.random.randint(100, size=4)] = np.nan #随机取4个置nan
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')

In [120]:
a

array([[5, 7, 0, ..., 0, 2, 7],
       [1, 4, 9, ..., 1, 2, 1],
       [8, 8, 0, ..., 5, 7, 8],
       ...,
       [9, 3, 1, ..., 0, 0, 4],
       [0, 6, 5, ..., 1, 7, 4],
       [1, 0, 1, ..., 1, 0, 4]], dtype=int16)

In [119]:
len(np.unique(a))

10

# 40 数字转文本（0-3转s，4-6转m，7-9转l）
```
a = np.random.rand(100)
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')
```

In [121]:
a = np.random.rand(100)
a[np.random.randint(100, size=4)] = np.nan
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')

In [122]:
b = np.full_like(a,"",dtype='S10')
b[a<=3] = 's'
b[(a<3) & (a<=6)]='m'
b[(a>6) &(a<=9)]='l'
b

array([[b'', b'', b'', ..., b'm', b'l', b's'],
       [b'', b'm', b'm', ..., b's', b'm', b''],
       [b'm', b'l', b'l', ..., b'l', b's', b's'],
       ...,
       [b'', b'l', b's', ..., b'l', b'', b'l'],
       [b'l', b'l', b's', ..., b's', b'', b'm'],
       [b'l', b'l', b'l', ..., b'l', b'l', b'l']], dtype='|S10')

# 41 用现有的列，创建新的一列（第0列叫x,第1列叫y，新增 sin(pi*(x/100)) * y^2）
```
a = np.random.rand(100)
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')
```

In [123]:
a = np.random.rand(100)
a = a.reshape(10,10)
a = a*10
a = a.astype('int16')

In [124]:
np.sin(np.pi*(a[0]/100)) * (a[1]**2)

array([13.670564,  0.094108,  7.853157,  1.539127,  0.872573, 17.855431,
        2.544271,  0.      , 15.177886,  0.      ])

# 42 从1d数组中抽样选出10个元素
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
```


In [125]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')

In [126]:
np.random.choice(a,10)

array([3, 2, 2, 3, 9, 0, 4, 1, 3, 2], dtype=int16)

# 43 如何获取1d数组中不重复的第二大的值
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
```

In [127]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')

In [128]:
np.unique(np.sort(a))[-2]

8

# 44 依据某一列对2d数组排序(例如根据第0列排序)
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)
```

In [129]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)

In [131]:
a[ a[:,0].argsort() ]

array([[0, 7, 5, ..., 8, 2, 2],
       [0, 2, 3, ..., 8, 4, 2],
       [0, 2, 1, ..., 7, 4, 7],
       ...,
       [7, 1, 4, ..., 5, 9, 8],
       [8, 6, 5, ..., 6, 5, 1],
       [9, 2, 2, ..., 2, 9, 8]], dtype=int16)

# 45 众数
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)
```

In [132]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)

In [133]:
v, c = np.unique(a, return_counts=True)
v,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16),
 array([12, 11,  7, 14,  8, 18,  8,  5, 11,  6]))

In [134]:
v[np.argmax(c)]

5

# 46 找出比给定值大的数第一次出现的位置
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')

b = 5
```

In [135]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
b = 5

In [138]:
a

array([6, 7, 3, ..., 7, 8, 3], dtype=int16)

In [136]:
np.argwhere(a>b)

array([[ 0],
       [ 1],
       [ 3],
       ...,
       [95],
       [97],
       [98]])

In [137]:
np.argwhere(a>b)[0]

array([0])

# 47 将所有>7的替换为7，<3的替换为3
```
in:a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)
```

In [139]:
a = np.random.rand(100)
a = a*10
a = a.astype('int16')
a = a.reshape(10,10)

In [140]:
np.where( a<3, 3, np.where(a>7, 7, a))

array([[7, 7, 3, ..., 7, 4, 3],
       [7, 5, 3, ..., 3, 6, 7],
       [3, 3, 3, ..., 3, 6, 6],
       ...,
       [5, 7, 3, ..., 7, 7, 3],
       [3, 3, 6, ..., 7, 4, 3],
       [6, 4, 3, ..., 6, 3, 4]], dtype=int16)

# 48 获取1d数组topK大的值（例如k=5）
```
a = np.random.uniform(1,50, 20)
```

In [141]:
a = np.random.uniform(1,50, 20) #[1,50) 20个数
a

array([35.151916,  5.19257 , 28.627778, ..., 49.096271,  4.746612,
        8.141269])

In [142]:
np.sort(a)[-5:]

array([35.238293, 41.050229, 42.032028, 45.025876, 49.096271])

# 49 如何逐行计算数组中所有值的数量？

In [150]:
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [155]:
def count_rowwise(arr2d):
    results=[]
    for row in arr2d:
        uniqs, counts = np.unique(row, return_counts=True)
        zeros = np.zeros( arr2d.shape[1], dtype=int)
        zeros[uniqs-1] = counts
        results.append(zeros.tolist())
    return results
count_rowwise(arr)

[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

# 50 如何把数组的数组转为1d数组
```
# Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
```

In [143]:
# Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [144]:
np.array( a for a in arr for arr in array_of_arrays  ) # 先写外圈

array(<generator object <genexpr> at 0x7feb3c09f0c0>, dtype=object)

In [145]:
np.array([a for arr in array_of_arrays  for a in arr])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 51 为数组的每个元素生成二进制编码
```
in: a = np.array([2, 3, 2, 2, 2, 1])
out:array([[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  0.,  0.]])
```

In [146]:
a = np.array([2, 3, 2, 2, 2, 1])

In [148]:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros( (len(arr), len(uniqs)) )
    for i, k in enumerate(arr):
        out[i,k-1] = 1
    return out
one_hot_encodings(a)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

# 52 分好组的元素给定组内行号
```
in: a = np.array(['a','a','a','b','b','c','c','c','c'])
out: array([0,1,2,0,1,0,1,2,3])
```

In [156]:
a = np.array(['a','a','a','b','b','c','c','c','c'])

In [159]:
[i for var in np.unique(a) for i, _ in enumerate( a[a==var])]

[0, 1, 2, 0, 1, 0, 1, 2, 3]

# 53 分好组的元素每组给个标号
```
in: a = np.array(['a','a','a','b','b','c','c','c','c'])
out: array([0,0,0,1,1,2,2,2,2])
```

In [160]:
a = np.array(['a','a','a','b','b','c','c','c','c'])

In [163]:
[ np.unique(a) == s for val in np.unique(a) for s in a[a==val] ]

[array([ True, False, False]),
 array([ True, False, False]),
 array([ True, False, False]),
 array([False,  True, False]),
 array([False,  True, False]),
 array([False, False,  True]),
 array([False, False,  True]),
 array([False, False,  True]),
 array([False, False,  True])]

In [165]:
[ np.argwhere( np.unique(a) == s)[0,0] for val in np.unique(a) for s in a[a==val] ]

[0, 0, 0, 1, 1, 2, 2, 2, 2]

# 54 给出每个元素在排序后的位置下标数组
给出元素的排名
```
in: [ 9  4 15  0 17 16 17  8  9  0]
out: [4 2 6 0 8 7 9 3 5 1]
```

In [166]:
np.random.seed(10)
a = np.random.randint(20, size=10)

In [167]:
a.argsort()

array([3, 9, 1, 7, 0, 8, 2, 5, 4, 6])

In [168]:
a.argsort().argsort()

array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])

# 55 上题改成多维数组
```
in:np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

out:#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]
```

In [169]:
# Input:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
a

array([[ 9,  4, 15,  0, 17],
       [16, 17,  8,  9,  0]])

In [173]:
a.ravel()

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [175]:
a.reshape(-1)

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [174]:
a.ravel().argsort().argsort().reshape(a.shape)

array([[4, 2, 6, 0, 8],
       [7, 9, 3, 5, 1]])

# 56 二维数组找出每一行的最大值
```
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
```

In [177]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [178]:
a.max(axis=1)

array([9, 8, 6, 3, 9])

# 57 上题变种，计算每一行max/min的值

In [181]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [180]:
[ max(row)/min(row) for row in a ]

[2.25, 8.0, 2.0, 1.0, 9.0]

# 58 找到数组中重复的值
第二次出现开始算
```
in: [0 0 3 0 2 4 2 2 2 2]
out:[False  True False  True False False  True  True  True  True]
```

In [182]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)

In [183]:
out = np.full(len(a), True)
unique_positions = np.unique(a, return_index=True) # 实际值与 index值 
unique_positions # u

(array([0, 2, 3, 4]), array([0, 4, 2, 5]))

In [184]:
out[unique_positions[1]] = False
out

array([False,  True, False,  True, False, False,  True,  True,  True,
        True])

# 59 如何找到 NumPy 的分组平均值？

In [185]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [186]:
uniques = np.unique(iris[:, 4]) # 得到第5列的种类
uniques

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object)

In [187]:
output = []
for v in uniques:
    group = iris[iris[:,4]==v] # 得到某一类的所有数据
    output.append( [v, np.mean(group[:,1].astype(float) )])
output

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

# 60 将一张jpg图片转换为numpy数组
```
in:URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
```

In [188]:
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [190]:
# conda install -c conda-forge scikit-image
from skimage import io
io.imread(URL)

array([[[  9,  72, 125],
        [  9,  72, 125],
        [  9,  72, 125],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [  9,  72, 125],
        [ 10,  73, 126],
        ...,
        [ 42, 103, 147],
        [ 42, 103, 147],
        [ 43, 104, 148]],

       [[  9,  72, 125],
        [ 10,  73, 126],
        [ 10,  73, 126],
        ...,
        [ 44, 105, 150],
        [ 45, 106, 151],
        [ 45, 106, 151]],

       ...,

       [[ 21,  41,  50],
        [ 29,  51,  64],
        [ 28,  54,  69],
        ...,
        [ 27,  58,  79],
        [ 22,  53,  74],
        [ 19,  47,  69]],

       [[ 27,  51,  63],
        [ 29,  55,  68],
        [ 27,  56,  72],
        ...,
        [ 33,  70,  97],
        [ 27,  64,  91],
        [ 22,  57,  85]],

       [[ 18,  45,  56],
        [ 20,  48,  62],
        [ 21,  52,  70],
        ...,
        [ 15,  51,  77],
        [ 12,  48,  74],
        [ 11,  45,  72]]

# 61 如何剔除所有nan值
```
in:np.array([1,2,3,np.nan,5,6,7,np.nan])
out:array([ 1.,  2.,  3.,  5.,  6.,  7.])
```

In [191]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [192]:
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

# 62 如何计算两数组欧式距离
```
in:a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
out:6.7082039324993694
```

In [193]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [194]:
dist = np.linalg.norm(a-b)
dist

6.708203932499369

# 63 一维数组找到所有峰值(比前后都大的值)的下标
局部极大值
```
in:a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
out:[2,5]
```

In [197]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

In [198]:
np.diff(a)

array([ 2,  4, -6,  1,  4, -6,  1])

In [199]:
np.sign(np.diff(a))

array([ 1,  1, -1,  1,  1, -1,  1])

In [201]:
double_diff = np.diff(np.sign(np.diff(a)))
double_diff

array([ 0, -2,  2,  0, -2,  2])

In [203]:
np.where(double_diff == -2)[0] + 1

array([2, 5])

# 64 二维数组每一行都减去一个一维数组
```
in:a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
  b_1d = np.array([1,2,3])
  
 out: [
     [2,1,0],
     [3,2,1],
     [4,3,2]
 ]
```

In [204]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

In [205]:
a_2d - b_1d

array([[2, 1, 0],
       [3, 2, 1],
       [4, 3, 2]])

# 65 找到第n个特定数出现的下标
```
找第5个1出现的位置
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
```

In [206]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [207]:
np.where(x==1)

(array([ 0,  2,  3,  7,  8, 10, 11]),)

In [208]:
np.where(x==1)[0][5-1]

8

# 66 将datetime64类型转datetime类型
```
in:dt64 = np.datetime64('2018-02-25 22:10:10')
```

In [209]:
dt64 = np.datetime64('2018-02-25 22:10:10')

In [210]:
dt64.tolist()

datetime.datetime(2018, 2, 25, 22, 10, 10)

# 67 计算滑动窗口均值(例如窗口大小3，就是0-2均值，1-3均值，2-4....)
```
in:np.random.seed(100)
Z = np.random.randint(10, size=10)

out:[ 6.33  6.    5.67  4.67  3.67  2.    3.67  3.  ]
```

In [211]:
np.random.seed(100)
Z = np.random.randint(10, size=10)

In [212]:
np.ones(3)/3

array([0.333333, 0.333333, 0.333333])

In [213]:
np.convolve(Z, np.ones(3)/3, mode='valid') #逐项相乘

array([6.333333, 6.      , 5.666667, 4.666667, 3.666667, 2.      ,
       3.666667, 3.      ])

# 68 创建一个等差数列初值5增幅3数组总长10

In [217]:
np.arange(5, 35,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

# 69 如何在一系列无序日期中，补全缺失的日期


In [218]:
# Input
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

['2018-02-01' '2018-02-03' '2018-02-05' ... '2018-02-19' '2018-02-21'
 '2018-02-23']


In [221]:
np.diff(dates)

array([2, 2, 2, ..., 2, 2, 2], dtype='timedelta64[D]')

In [222]:
zip(dates, np.diff(dates))

In [220]:
out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))
out

[array(['2018-02-01', '2018-02-02'], dtype='datetime64[D]'),
 array(['2018-02-03', '2018-02-04'], dtype='datetime64[D]'),
 array(['2018-02-05', '2018-02-06'], dtype='datetime64[D]'),
 array(['2018-02-07', '2018-02-08'], dtype='datetime64[D]'),
 array(['2018-02-09', '2018-02-10'], dtype='datetime64[D]'),
 array(['2018-02-11', '2018-02-12'], dtype='datetime64[D]'),
 array(['2018-02-13', '2018-02-14'], dtype='datetime64[D]'),
 array(['2018-02-15', '2018-02-16'], dtype='datetime64[D]'),
 array(['2018-02-17', '2018-02-18'], dtype='datetime64[D]'),
 array(['2018-02-19', '2018-02-20'], dtype='datetime64[D]'),
 array(['2018-02-21', '2018-02-22'], dtype='datetime64[D]')]

In [223]:
filled_in = np.array(out).reshape(-1)
filled_in

array(['2018-02-01', '2018-02-02', '2018-02-03', ..., '2018-02-20',
       '2018-02-21', '2018-02-22'], dtype='datetime64[D]')

In [224]:
output = np.hstack([filled_in, dates[-1]]) #添加了最后一个
output

array(['2018-02-01', '2018-02-02', '2018-02-03', ..., '2018-02-21',
       '2018-02-22', '2018-02-23'], dtype='datetime64[D]')

# 70 给定一维数组，创建阶梯型二维数组，二维数组列数是4，步幅是2
```
in:arr = np.arange(15) 
out:#> [[ 0  1  2  3]
#>  [ 2  3  4  5]
#>  [ 4  5  6  7]
#>  [ 6  7  8  9]
#>  [ 8  9 10 11]
#>  [10 11 12 13]]
```

In [225]:
arr = np.arange(15) 

In [227]:
def gen_rows(a, steps= 2, columns = 4):
    rows = (a.size - columns)//steps + 1
    return np.array([a[s: s+columns] for s in np.arange(0, rows * steps, steps)])

gen_rows(arr)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])